### ISSUE TITLE
Página de aprovação de  entregas

### ISSUE THREAD

**Issue by bener07** [bener07/domus-apparatus#19]
No backend o administrador com menor número de pedidos irá receber uma notificação a pedir autorização para o requisito ou a entrega de um equipamento. É preciso uma página onde as seguintes informações sejam apresentadas:
Caso seja para requisitar:
    - Equipamento pretendido
    - Categorias a que pretence
    - Quem o quer requisitar
    - Para que data é que pretende requisitar
    - Data prevista de entrega
    - Selecionar outro dispositivo (caso um professor queira requisitar o computador x1, mas não é possível, então o administrador tem a possibilidade de selecionar outro equipamento (x2) para ser requisitado, mas equipamento tem de ser do mesmo tipo. Se tiveres 10 computadores e o computador 1 está estragado e isso não consta na base de dados, então o administrador pode selecionar outro computador, como o 4, para ser requisitado)
    - Mais algum tipo de funcionalidade que achem util e necessário

**Comment by Telmocas** [comment]
![Image](https://github.com/user-attachments/assets/ed906f1c-a563-4db1-a72f-d2e4de829dd9)
